### ISSUE TITLE
cd as vagrant into the rails app dir causes "Permission denied" error

### ISSUE THREAD

**Issue by vraravam** [jskswamy/deploy-rails#1]
since `/usr/local/rvm` is owned by root. I am not sure whether to run `usermod` to make the vagrant user become part of the root group? Or something else What do you suggest?

**Comment by vraravam** [comment]
Fixed as part of latest commit: d8cf7216

**Comment by jskswamy** [comment]
Other option is to install the rvm as ansible user, refer [rvm1-ansible](https://github.com/rvm/rvm1-ansible#role-variables)
