### ISSUE TITLE
Do not need to overwrite the database.yml and secrets.yml files in development

### ISSUE THREAD

**Issue by vraravam** [jskswamy/deploy-rails#2]
Since we generate rails codebases, I assume that the `config/database.yml` and `config/secrets.yml` files will have the correct content for the `development` and `test` envs. IF we [overwrite them](https://github.com/jskswamy/deploy-rails/blob/master/roles/rails/tasks/development.yml#L25), then `rake spec` will stop working since the corresponding entries for these environments will be wiped out.

**Comment by jskswamy** [comment]
Fixed, refer [9ac2977c8f73ca382154831b2339ff2f6dc6c669](https://github.com/jskswamy/deploy-rails/commit/9ac2977c8f73ca382154831b2339ff2f6dc6c669)
